[package]
name = "fluvio-experimental"
version = "0.1.0"
authors = ["Nick Mosher <nicholastmosher@gmail.com>"]
edition = "2018"

[features]
nightly = []

[dependencies]
futures = "0.3.5"

# Fluvio dependencies
fluvio = { path = "../client" }

[dev-dependencies]
async-std = "1.6.3"
